/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-10-18 17:54:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.v3.handHeld;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MobClasifiPickForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/c.tld", Long.valueOf(1634565188227L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
			
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("v3/assets/handheld/buscador.css\"\tmedia=\"handheld\" />\r\n");
      out.write("<link rel=\"stylesheet\" id=\"smthemenewprint-css\"\thref=\"");
      out.print(basePath);
      out.write("v3/assets/handheld/formsHandHel.css\" type=\"text/css\" /> -->\r\n");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("  ");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /v3/handHeld/MobClasifiPickForm.jsp(20,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css=='IE'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("    <link rel=\"stylesheet\" href=\"");
                  out.print(basePath);
                  out.write("v3/assets/handheld/buscador.css\" media=\"screen\" />\r\n");
                  out.write("  ");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\r\n");
            out.write("  ");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f0_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
                  out.write("\t<link rel=\"stylesheet\" href=\"");
                  out.print(basePath);
                  out.write("v3/assets/css/responsiveForms.css\" type=\"text/css\">\r\n");
                  out.write("  ");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
              _jspx_th_c_005fotherwise_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
            }
            out.write('\r');
            out.write('\n');
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"dt_example\" style=\"border-left: 0;\" >\r\n");
      out.write("\t\r\n");
      out.write("\t<form id=\"contactform\" name=\"contactform\" class=\"rounded\"\tmethod=\"post\" action=\"");
      out.print(basePath);
      out.write("/confirmarPick.do\" style=\"float: left;\">\r\n");
      out.write("\t\t<div class=\"field\" align=\"center\">\r\n");
      out.write("\t\t\t<div class=\"field\" align=\"center\">\r\n");
      out.write("\t\t\t\t<label for=\"lblArticulo\">Barra</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"test\" id=\"test\"  onkeypress=\"setArticulo(event);\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"clear: both; float: none;\"></div>\r\n");
      out.write("\t\t\t<div class=\"field\" align=\"center\">\r\n");
      out.write("\t\t\t\t<label for=\"lblArticulo\">Cod. Destino</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"codDestino\" id=\"codDestino\"  onkeypress=\"setDestinoCantidad(event);\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"height: 5px;\"></div>\r\n");
      out.write("\t\t<a href=\"#\" onclick=\"CloseBox()\">\r\n");
      out.write("\t\t\t<input class=\"col-100 button\" type=\"button\" value=\"CERRAR CAJA\"/>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<!-- <a href=\"#\" onclick=\"Finish()\">\r\n");
      out.write("\t\t\t<input class=\"col-100 button\" type=\"button\" value=\"FINALIZAR\"/>\r\n");
      out.write("\t\t</a> -->\r\n");
      out.write("\t\t<a href=\"");
      out.print(basePath);
      out.write("DarPickings.do?destino=verificar\">\r\n");
      out.write("\t\t\t<input class=\"col-100 button\" type=\"button\" value=\"Ir a menú\"/>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar pick = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pickings.get(0).idPicking}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\tfunction Finish(){\r\n");
      out.write("\t\t\tif(confirm('Seguro que quiere finalizar esta verificacion?')){\r\n");
      out.write("\t\t\t\tlocation.replace(\"");
      out.print(basePath);
      out.write("FinDescartarPick.do?idPick=\"+pick+\"&pag=verificar\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction CloseBox(){\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlocation.replace(\"");
      out.print(basePath);
      out.write("v3/handHeld/CloseBox.jsp\");\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<audio id=\"xyz\" src=\"");
      out.print(basePath);
      out.write("audio/errors.mp3\" preload=\"auto\"></audio>\r\n");
      out.write("       ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("       <script type=\"text/javascript\">\r\n");
      out.write("             window.onload = function() {\r\n");
      out.write("               document.getElementById(\"test\").focus();\r\n");
      out.write("             };\r\n");
      out.write("       </script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t(function ($) { \r\n");
      out.write("\t\t$.fn.hideKeyboard = function() { \r\n");
      out.write("\t\t\tvar inputs = this.filter(\"input\").attr('readonly', 'readonly'); \r\n");
      out.write("\t\t\t// Force keyboard to hide on input field. \r\n");
      out.write("\t\t\tvar textareas = this.filter(\"textarea\").attr('disabled', 'true'); \r\n");
      out.write("\t\t\t// Force keyboard to hide on textarea field. \r\n");
      out.write("\t\t\tsetTimeout(function() { \r\n");
      out.write("\t\t\t\tinputs.blur().removeAttr('readonly'); \r\n");
      out.write("\t\t\t\t//actually close the keyboard and remove attributes\r\n");
      out.write("\t\t\t\ttextareas.blur().removeAttr('disabled'); \r\n");
      out.write("\t\t\t}, 100); \r\n");
      out.write("\t\t\treturn this; \r\n");
      out.write("\t\t}; \r\n");
      out.write("\t}( jQuery )); \r\n");
      out.write("\t\t\r\n");
      out.write("\t $('#codDestino').hideKeyboard()\r\n");
      out.write("\t //$('#myForm input,#myForm textarea').hideKeyboard(); \t\t\r\n");
      out.write("</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar clasificador = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clasificador_json}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tvar thisArticulo;\r\n");
      out.write("\tvar paramVerificacion = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paramVerificacion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t/*\r\n");
      out.write("\tconsole.log(clasificador);\r\n");
      out.write("\tvar destinio = clasificador[\"G1154B\"];\r\n");
      out.write("\tconsole.log(destinio);\r\n");
      out.write("\tvar primero\r\n");
      out.write("\tfor (let key in destinio) {\r\n");
      out.write("\t\tprimero = destinio[key];\r\n");
      out.write("\t\tconsole.log(primero);\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar p = primero[0];\r\n");
      out.write("\tconsole.log(p);\r\n");
      out.write("\tconsole.log(\"destino qty:\"+ p.destinosQty);\r\n");
      out.write("\t*/\r\n");
      out.write("\tvar idEmpresa= [");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uLogeado.idEmpresa}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("];\r\n");
      out.write("\tvar articulos = [");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${arregloArticulos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("];\r\n");
      out.write("\tvar articulosPosicion = [");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${arregloDestinos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("];\r\n");
      out.write("\tvar arregloDestinosQty = [");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${arregloDestinosQty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("];\r\n");
      out.write("\tvar destinoArtCant=[];\r\n");
      out.write("\tvar codDestino = -1;\r\n");
      out.write("\tvar barras = new Array();\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction primerDestino(objeto) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar primero;\r\n");
      out.write("\t\tfor (let key in objeto) {\r\n");
      out.write("\t\t\t primero = objeto[key];\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn primero[0];\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setArticulo(event) \r\n");
      out.write("\t{\r\n");
      out.write("\t    var char = event.which || event.keyCode;\r\n");
      out.write("\t    // If the user has pressed enter\r\n");
      out.write("\t    if (char == 13) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar input = document.getElementById(\"test\").value;\r\n");
      out.write("\t\t\tif(input!=\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar articulo = barras[input.toUpperCase()];\r\n");
      out.write("\t\t\t\t//document.getElementById(\"test\").value = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar objeto_destinos = clasificador[articulo];\r\n");
      out.write("\t\t\t\tif(objeto_destinos == null)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar alarma = document.getElementById('xyz');\r\n");
      out.write("\t\t\t\t\talarma.play().catch(function() {\r\n");
      out.write("\t\t\t\t    document.getElementById('xyz').play();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\talarma.addEventListener('ended', showAlert(\"El articulo no esta en la lista del picking\"));\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//alert(\"El articulo no esta en la lista del picking\");\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"test\").value=\"\";\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"test\").focus()\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar articulo_destino = primerDestino(objeto_destinos);\r\n");
      out.write("\t\t\t\t\tvar destinosQty = articulo_destino.destinosQty;\r\n");
      out.write("\t\t\t\t\tif(destinosQty==1){\r\n");
      out.write("\t\t\t\t\t\tcodDestino = articulo_destino.posSort;\r\n");
      out.write("\t\t\t\t\t\tthisArticulo = articulo_destino;\r\n");
      out.write("\t\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(idEmpresa == 5){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar justificacion = articulo_destino.justificacion;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar observacion = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar noEncontrado=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar descripcionGeneral = justificacion.split(\"*\");\t\r\n");
      out.write("\t\t\t\t\t\t\t\tif(descripcionGeneral.length > 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tjustificacion = descripcionGeneral[0];\r\n");
      out.write("\t\t\t\t\t\t\t\t\tobservacion = descripcionGeneral[1];\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar descNoEncontrado = descripcionGeneral[1].split(\"--\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (descNoEncontrado.length > 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tobservacion = descNoEncontrado[0];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tnoEncontrado= descNoEncontrado[1];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar descNoEncontrado = descripcionGeneral[0].split(\"--\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (descNoEncontrado.length > 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tjustificacion=descNoEncontrado[0];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tnoEncontrado=descNoEncontrado[1];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"lblArtDesc\").innerHTML = justificacion;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"lblArtJust\").innerHTML = observacion;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"lblArtNC\").innerHTML = noEncontrado;\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"lblCodigo\").innerHTML = articulo_destino.posSort;\r\n");
      out.write("\t\t\t\t\t\t\tif(idEmpresa != 5){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"lblArtDesc\").innerHTML = articulo_destino.articulo+\"<br/>\"+articulo_destino.justificacion;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t//document.getElementById(\"lblArtJust\").innerHTML = articulo_destino.articulo+\"<br/>\"+articulo_destino.observacion;\r\n");
      out.write("\t\t\t\t\t\t\t//document.getElementById(\"lblArtNC\").innerHTML = articulo_destino.articulo+\"<br/>\"+articulo_destino.noEncontrado;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"imagenArt\").src = articulo_destino.imagen;\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"lblQtyped\").innerHTML = articulo_destino.sol;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"lblEmpaque\").innerHTML = articulo_destino.empaque;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"lblDestino\").innerHTML = articulo_destino.destino.descripcion;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"lblSolicitud\").innerHTML = articulo_destino.solicitud;\r\n");
      out.write("\t\t\t\t\t\t\tif(paramVerificacion){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"lblPendiente\").innerHTML = articulo_destino.pick - articulo_destino.verificada;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"lblPendiente\").innerHTML = articulo_destino.sol - articulo_destino.verificada;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t//document.getElementById(\"qty\").value = articulo_destino.sol - articulo_destino.verificada;\r\n");
      out.write("\t\t\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\t\t\t//e.printStackTrace();\r\n");
      out.write("\t\t\t\t\t\t}\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"codDestino\").focus();\r\n");
      out.write("\t\t\t\t\t\tvar elmnt = document.getElementById(\"lblCodigo\");\r\n");
      out.write("\t\t\t\t\t\telmnt.scrollIntoView();\r\n");
      out.write("\t\t\t\t\t\t//document.getElementById(\"destino\").value = codigos.toString()\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tvar alarma = document.getElementById('xyz');\r\n");
      out.write("\t\t\t\t\t\talarma.play().catch(function() {\r\n");
      out.write("\t\t\t\t\t    document.getElementById('xyz').play();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\talarma.addEventListener('ended', showAlert(\"Este bulto contiene articulos para mas de un destino, debe escanear los articulos de a uno\"));\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"test\").value=\"\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"test\").focus()\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else \r\n");
      out.write("\t\t{\r\n");
      out.write("\t        return true;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setDestinoCantidad(event) \r\n");
      out.write("\t{\r\n");
      out.write("\t    var char = event.which || event.keyCode;\r\n");
      out.write("\t\r\n");
      out.write("\t    // If the user has pressed enter\r\n");
      out.write("\t    if (char == 13) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar codDe = document.getElementById(\"codDestino\").value;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar cod = document.getElementById(\"test\").value;\r\n");
      out.write("\t\t\tvar articulo = barras[cod.toUpperCase()];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar qty = 1;\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\tqty = document.getElementById(\"qty\").value;\r\n");
      out.write("\t\t\t\tqty = parseInt(qty);\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar pendientes = thisArticulo.sol - thisArticulo.verificada\r\n");
      out.write("\t\t\tif(paramVerificacion){\r\n");
      out.write("\t\t\t\tpendientes = thisArticulo.pick - thisArticulo.verificada\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(qty <= pendientes){\r\n");
      out.write("\t\t\t\tif(codDe!=codDestino)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar alarma = document.getElementById('xyz');\r\n");
      out.write("\t\t\t\t\talarma.play().catch(function() {\r\n");
      out.write("\t\t\t\t    document.getElementById('xyz').play();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\talarma.addEventListener('ended', showAlert(\"Destino incorrecto,debe colocar en \"+codDestino));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//alert(\"Destino incorrecto, debe colocar en \"+codDestino);\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"codDestino\").value=\"\";\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"codDestino\").focus()\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t//hago el \"submit\"\r\n");
      out.write("\t\t\t\t\t//String art = request.getParameter(\"arti\");\r\n");
      out.write("\t\t\t\t\t//int posicion = Integer.parseInt(request.getParameter(\"posicion\"));\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"test\").disabled = true;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"codDestino\").disabled = true;\r\n");
      out.write("\t\t\t\t\tlocation.replace(\"");
      out.print(basePath);
      out.write("ConfirmarDistPicking.do?art=\"+thisArticulo.articulo+\"&posicion=\"+codDestino+\"&qty=\"+qty);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t        return false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tvar alarma = document.getElementById('xyz');\r\n");
      out.write("\t\t\t\talarma.play().catch(function() {\r\n");
      out.write("\t\t\t    document.getElementById('xyz').play();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\talarma.addEventListener('ended', showAlert(\"Debe ingresar una cantidad menor\"));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//alert(\"Destino incorrecto, debe colocar en \"+codDestino);\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"codDestino\").value=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"codDestino\").focus()\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t}\t\t\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else \r\n");
      out.write("\t\t{\r\n");
      out.write("\t        return true;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction darPosicionArticulo(str) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tfLen = articulos.length;\r\n");
      out.write("\t\tfor (i = 0; i < fLen; i++) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t    var ar = articulos[i];\r\n");
      out.write("\t\t    if(ar==str)\r\n");
      out.write("\t\t    {\r\n");
      out.write("\t\t \t\treturn i;   \t\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn -1;\r\n");
      out.write("\t\t \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction onTestChange(event) \r\n");
      out.write("\t{\r\n");
      out.write("\t    var char = event.which || event.keyCode;\r\n");
      out.write("\t    // If the user has pressed enter\r\n");
      out.write("\t    if (char == 13) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar cod = document.getElementById(\"test\").value;\r\n");
      out.write("\t\t\tif(cod!=\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar articuloScn = barras[cod.toUpperCase()];\r\n");
      out.write("\t\t\t\t//document.getElementById(\"test\").value = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar pos = darPosicionArticulo(articuloScn);\r\n");
      out.write("\t\t\t\tif(pos==-1)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar alarma = document.getElementById('xyz');\r\n");
      out.write("\t\t\t\t\talarma.play().catch(function() {\r\n");
      out.write("\t\t\t\t    document.getElementById('xyz').play();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\talarma.addEventListener('ended', showAlert(\"El articulo no esta en la lista del picking\"));\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//alert(\"El articulo no esta en la lista del picking\");\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"test\").value=\"\";\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"test\").focus()\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar destinosQty = arregloDestinosQty[pos];\r\n");
      out.write("\t\t\t\t\tif(destinosQty==1){\r\n");
      out.write("\t\t\t\t\t\tcodDestino = articulosPosicion[pos];\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"lblDest\").innerHTML = codDestino;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"codDestino\").focus();\r\n");
      out.write("\t\t\t\t\t\tvar elmnt = document.getElementById(\"lblDest\");\r\n");
      out.write("\t\t\t\t\t\telmnt.scrollIntoView();\r\n");
      out.write("\t\t\t\t\t\t//document.getElementById(\"destino\").value = codigos.toString()\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tvar alarma = document.getElementById('xyz');\r\n");
      out.write("\t\t\t\t\t\talarma.play().catch(function() {\r\n");
      out.write("\t\t\t\t\t    document.getElementById('xyz').play();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\talarma.addEventListener('ended', showAlert(\"Este bulto contiene articulos para mas de un destino, debe escanear los articulos de a uno\"));\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"test\").value=\"\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"test\").focus()\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else \r\n");
      out.write("\t\t{\r\n");
      out.write("\t        return true;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction onTestChangeII(event) \r\n");
      out.write("\t{\r\n");
      out.write("\t    var char = event.which || event.keyCode;\r\n");
      out.write("\t\r\n");
      out.write("\t    // If the user has pressed enter\r\n");
      out.write("\t    if (char == 13) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar codDe = document.getElementById(\"codDestino\").value;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar cod = document.getElementById(\"test\").value;\r\n");
      out.write("\t\t\tvar articuloScn = barras[cod.toUpperCase()];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(codDe!=codDestino)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar alarma = document.getElementById('xyz');\r\n");
      out.write("\t\t\t\talarma.play().catch(function() {\r\n");
      out.write("\t\t\t    document.getElementById('xyz').play();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\talarma.addEventListener('ended', showAlert(\"Destino incorrecto,debe colocar en \"+codDestino));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//alert(\"Destino incorrecto, debe colocar en \"+codDestino);\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"codDestino\").value=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"codDestino\").focus()\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t//hago el \"submit\"\r\n");
      out.write("\t\t\t\t//String art = request.getParameter(\"arti\");\r\n");
      out.write("\t\t\t\t//int posicion = Integer.parseInt(request.getParameter(\"posicion\"));\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"test\").disabled = true;\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"codDestino\").disabled = true;\r\n");
      out.write("\t\t\t\tlocation.replace(\"");
      out.print(basePath);
      out.write("ConfirmarDistPicking.do?art=\"+articuloScn+\"&posicion=\"+codDestino);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else \r\n");
      out.write("\t\t{\r\n");
      out.write("\t        return true;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction subm(event,type) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"typeSave\").value = type\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(type==0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(confirm(\"Desea confirmar las cantidades (\"+count+\")?\"))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.forms[\"contactform\"].submit();\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.forms[\"contactform\"].submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showAlert(msj) {\r\n");
      out.write("\t\talert(msj);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fremove_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /v3/handHeld/MobClasifiPickForm.jsp(39,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!paramDetalle}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"field\" align=\"center\">\r\n");
          out.write("\t\t\t\t\t<label for=\"lblCantidad\">Ubicacion:<br/><br/><strong id=\"lblCodigo\" style=\"font-size: 40pt; color: red;\"></strong></label>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /v3/handHeld/MobClasifiPickForm.jsp(45,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paramDetalle}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"field\" align=\"left\">\r\n");
          out.write("\t\t\t\t\t<span><strong style=\"margin-left: 10px;\" id=\"lblArtDesc\"></strong></span>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t<img  id=\"imagenArt\" alt='' src='' style='width: 280px;'>\r\n");
          out.write("\t\t\t\t\t<h4>Codigo de ubicacion:<strong style=\"margin-left: 10px;\" id=\"lblCodigo\"></strong></h4>\r\n");
          out.write("\t\t\t\t\t<h4>Destino:<strong style=\"margin-left: 10px;\" id=\"lblDestino\"></strong></h4>\r\n");
          out.write("\t\t\t\t\t<h4>Solicitud:<strong style=\"margin-left: 10px;\" id=\"lblSolicitud\"></strong></h4>\r\n");
          out.write("\t\t\t\t\t<h4>Pendiente de verificar :<strong style=\"margin-left: 10px;\" id=\"lblPendiente\"></strong></h4>\r\n");
          out.write("\t\t\t\t\t<h4 style=\"color: red\">Caja cerrada por :<strong style=\"margin-left: 10px;\" id=\"lblEmpaque\"></strong></h4>\r\n");
          out.write("\t\t\t\t\t<h4>Cantidad Pedido :<strong style=\"margin-left: 10px;\" id=\"lblQtyped\"></strong></h4>\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /v3/handHeld/MobClasifiPickForm.jsp(49,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uLogeado.idEmpresa==5}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<span><strong style=\"margin-left: 10px; font-size: 15pt;  color: #35d0f3\" id=\"lblArtJust\"></strong></span>\r\n");
          out.write("\t\t\t\t\t\t<span style=\"margin-left: 10px; font-size: 10pt\" id=\"lblArtNC\"></span>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /v3/handHeld/MobClasifiPickForm.jsp(61,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paramCantidad}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<h4 style=\"float: left; width: auto;\">Verifico</h4>\r\n");
          out.write("\t\t\t\t\t\t<input style=\"float: left; width: auto; margin-left: 10px; margin-top: 10px; text-align: center;\" type=\"number\" name=\"qty\" id=\"qty\" id=\"qty\" value=\"1\" min=\"1\"/>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /v3/handHeld/MobClasifiPickForm.jsp(86,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cerrarPick");
      // /v3/handHeld/MobClasifiPickForm.jsp(86,1) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pickings.get(0).idPicking}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /v3/handHeld/MobClasifiPickForm.jsp(86,1) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("session");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /v3/handHeld/MobClasifiPickForm.jsp(87,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("actPick");
      // /v3/handHeld/MobClasifiPickForm.jsp(87,1) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue("clasifica");
      // /v3/handHeld/MobClasifiPickForm.jsp(87,1) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setScope("session");
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /v3/handHeld/MobClasifiPickForm.jsp(105,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menError!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<script type=\"text/javascript\"> \r\n");
          out.write("\t\t\tvar alarma = document.getElementById('xyz');\r\n");
          out.write("\t\t\talarma.play().catch(function() {\r\n");
          out.write("\t\t    document.getElementById('xyz').play();\r\n");
          out.write("\t\t\t});\r\n");
          out.write("\t\t\talarma.addEventListener('ended', showAlert);\r\n");
          out.write("\r\n");
          out.write("\t\t\tfunction showAlert() {\r\n");
          out.write("\t\t\t alert('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menError}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("');\r\n");
          out.write("\t\t\t}\t\t\t\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t</script>\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /v3/handHeld/MobClasifiPickForm.jsp(171,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      // /v3/handHeld/MobClasifiPickForm.jsp(171,1) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pickings}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write('\r');
            out.write('\n');
            out.write('	');
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /v3/handHeld/MobClasifiPickForm.jsp(172,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("bar");
      // /v3/handHeld/MobClasifiPickForm.jsp(172,2) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.barras}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\tbarras[\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"]=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.articulo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\";\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent(null);
      // /v3/handHeld/MobClasifiPickForm.jsp(525,0) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("menError");
      // /v3/handHeld/MobClasifiPickForm.jsp(525,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
