/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-10-18 15:14:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.v3.util;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1634567341926L));
    _jspx_dependants.put("/WEB-INF/c.tld", Long.valueOf(1634565188227L));
    _jspx_dependants.put("jar:file:/C:/Users/200/Desktop/Encuentra/Encuentra/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WMS/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153395882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"md-modal md-effect-1\" id=\"modal-Equipo\">\r\n");
      out.write("\t\t\t        <div class=\"md-content\">\r\n");
      out.write("\t\t\t            <h3 class=\"theme-bg2\">Cambiar equipo de impresión</h3>\r\n");
      out.write("\t\t\t            <div class=\"row\">\r\n");
      out.write("\t\t\t\t            <div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t\t\t            <div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-6 control-label\" for=\"p1\">Nº Equipo Actual:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t<input class=\"form-control md-12\" readonly=\"readonly\" name=\"actual\" id=\"actual\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uLogeado.idEquipo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-4 control-label\" for=\"perfil\">Equipo:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t<select class=\"form-control md-12\" name=\"equipo\" id=\"equipo\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary md-close\" >Cerrar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button onclick=\"sendEquipo()\" class=\"btn btn-success md-close\">Confirmar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t                <!--<a class=\"btn btn-primary md-close\" onclick=\"closeModal('modal-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.numeroDoc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\" href=\"#\">Cerrar</a>  -->\r\n");
      out.write("\t\t\t\t                \r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t            <div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t\t\t    \t</div>        \r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    <div class=\"md-modal md-effect-1\" id=\"modal-Depo\">\r\n");
      out.write("\t\t\t        <div class=\"md-content\">\r\n");
      out.write("\t\t\t            <h3 class=\"theme-bg2\">Cambiar Depósito</h3>\r\n");
      out.write("\t\t\t            <div class=\"row\">\r\n");
      out.write("\t\t\t\t            <div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t\t\t            <div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t              \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-6 control-label\" for=\"p1\">Nº Depósito Actual:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t<input class=\"form-control\" readonly=\"readonly\" name=\"actual\" id=\"actualD\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uLogeado.deposito}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-4 control-label\" for=\"perfil\">Depósito:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t<select class=\"form-control\" name=\"deposito\" id=\"deposito\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary md-close\" >Cerrar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button onclick=\"sendDepo()\" class=\"btn btn-success md-close\">Confirmar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t                <!--<a class=\"btn btn-primary md-close\" onclick=\"closeModal('modal-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.numeroDoc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\" href=\"#\">Cerrar</a>  -->\r\n");
      out.write("\t\t\t\t                \r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t            <div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t\t\t    \t</div>       \r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    <div class=\"md-modal md-effect-1\" id=\"modal-Pass\">\r\n");
      out.write("\t\t\t        <div class=\"md-content\">\r\n");
      out.write("\t\t\t             <h3 class=\"theme-bg2\">Cambiar Contraseña</h3>\r\n");
      out.write("\t\t\t             \r\n");
      out.write("\t\t\t            <div class=\"row\">\r\n");
      out.write("\t\t\t\t            <div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t\t\t            <div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t            \t<div class=\"form-group\">\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label id=\"menErr\" class=\"col-md-12 control-label\" style=\"color: red;\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t             \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-6 control-label\" for=\"p1\">Password:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t<input required class=\"form-control\" name=\"p1\" id=\"p1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"password\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-6 control-label\" for=\"p1\">Repetir Password:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t<input required class=\"form-control\" name=\"p2\" id=\"p2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"password\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary md-close\" >Cerrar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button onclick=\"sendPass()\" class=\"btn btn-success md-close\">Confirmar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t                <!--<a class=\"btn btn-primary md-close\" onclick=\"closeModal('modal-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.numeroDoc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\" href=\"#\">Cerrar</a>  -->\r\n");
      out.write("\t\t\t\t                \r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t            <div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t\t\t    \t</div>        \t\t\t            \r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    <div class=\"md-overlay\" id=\"md-ov\"></div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("    <script>\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(document.getElementsByClassName(\"arrow-togglable\")!=null)\r\n");
      out.write("    \t{\r\n");
      out.write("    \t\tvar elements = document.getElementsByClassName(\"arrow-togglable\");\r\n");
      out.write("    \t    var currentIndex = 0;\r\n");
      out.write("    \t\r\n");
      out.write("    \t    document.onkeydown = function(e) {\r\n");
      out.write("    \t      switch (e.keyCode) {\r\n");
      out.write("    \t        case 38:\r\n");
      out.write("    \t          currentIndex = (currentIndex == 0) ? elements.length - 1 : --currentIndex;\r\n");
      out.write("    \t          elements[currentIndex].select();\r\n");
      out.write("    \t          elements[currentIndex].focus();\r\n");
      out.write("    \t          elements[currentIndex].select();\r\n");
      out.write("    \t          \r\n");
      out.write("    \t          \r\n");
      out.write("    \t          break;\r\n");
      out.write("    \t        case 40:\r\n");
      out.write("    \t          currentIndex = ((currentIndex + 1) == elements.length) ? 0 : ++currentIndex;\r\n");
      out.write("    \t          elements[currentIndex].select();\r\n");
      out.write("    \t          elements[currentIndex].focus();\r\n");
      out.write("    \t          elements[currentIndex].select();\r\n");
      out.write("    \t          \r\n");
      out.write("\r\n");
      out.write("    \t          break;\r\n");
      out.write("    \t      }\r\n");
      out.write("    \t    };\r\n");
      out.write("    \t}\r\n");
      out.write("\t    \r\n");
      out.write("    \r\n");
      out.write("    \t\t\r\n");
      out.write("\t\tfunction sendEquipo()\r\n");
      out.write("    \t{\r\n");
      out.write("\t\t    var v1 = document.getElementById(\"actual\").value;\r\n");
      out.write("\t\t    var v2 = document.getElementById(\"equipo\").value;\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    var params ={\r\n");
      out.write("\t\t\t\t\t\t\tactual : v1,\r\n");
      out.write("\t\t\t\t\t\t\tequipo : v2 \r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.print(basePath);
      out.write("cambioEquipo.do?mob=0\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\tdataType : \"html\",\r\n");
      out.write("\t\t\t\t\t\tdata : \r\n");
      out.write("\t\t\t\t\t\t\tparams \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}).then(function(data) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#modal-Equipo\").removeClass(\"md-show\");\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('li_equipo').innerHTML = params.equipo;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('actual').value = params.equipo;\r\n");
      out.write("\t\t\t\t\t});\t\t\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction sendDepo()\r\n");
      out.write("    \t{\r\n");
      out.write("\t\t    var v1 = document.getElementById(\"actualD\").value;\r\n");
      out.write("\t\t    var v2 = document.getElementById(\"deposito\").value;\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    var params ={\r\n");
      out.write("\t\t\t\t\t\t\tactual : v1,\r\n");
      out.write("\t\t\t\t\t\t\tdeposito : v2 \r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.print(basePath);
      out.write("cambioDeposito.do?mob=0\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\tdataType : \"html\",\r\n");
      out.write("\t\t\t\t\t\tdata : \r\n");
      out.write("\t\t\t\t\t\t\tparams \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}).then(function(data) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#modal-Depo\").removeClass(\"md-show\");\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('li_depo').innerHTML = params.deposito;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('actualD').value = params.deposito;\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t});\t\t\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction sendPass()\r\n");
      out.write("    \t{\r\n");
      out.write("\t\t    var v1 = document.getElementById(\"p1\").value;\r\n");
      out.write("\t\t    var v2 = document.getElementById(\"p2\").value;\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    var params ={\r\n");
      out.write("\t\t\t\t\t\t\tp1 : v1,\r\n");
      out.write("\t\t\t\t\t\t\tp2 : v2 \r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.print(basePath);
      out.write("cambioContrasena.do?mob=0\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\tdataType : \"html\",\r\n");
      out.write("\t\t\t\t\t\tdata : \r\n");
      out.write("\t\t\t\t\t\t\tparams \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}).then(function(data) {\r\n");
      out.write("\t\t\t\t\t\tdata = data.split('\\n').join('');\r\n");
      out.write("\t\t\t\t\t\tif(data===\" \"){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#modal-Pass\").removeClass(\"md-show\");\r\n");
      out.write("\t\t\t       \t\t}\r\n");
      out.write("\t\t\t       \t\telse{\r\n");
      out.write("\t\t\t       \t\t\tdocument.getElementById('menErr').innerHTML = data;\r\n");
      out.write("\t\t\t       \t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\t\t\t\r\n");
      out.write("\t\t} \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        \tfunction ModoInventario(){\r\n");
      out.write("        \t\r\n");
      out.write("        \t\tvar xmlhttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\t    //xmlhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');\r\n");
      out.write("\t\t\t    xmlhttp.onreadystatechange = function() {\r\n");
      out.write("\t\t\t        if (xmlhttp.readyState == XMLHttpRequest.DONE ) \r\n");
      out.write("\t\t\t        {\r\n");
      out.write("\t\t\t           if (xmlhttp.status == 200) \r\n");
      out.write("\t\t\t           {\r\n");
      out.write("\t\t\t           }\r\n");
      out.write("\t\t\t           else if (xmlhttp.status == 400) \r\n");
      out.write("\t\t\t           {\r\n");
      out.write("\t\t\t              alert('There was an error 400');\r\n");
      out.write("\t\t\t           }\r\n");
      out.write("\t\t\t           else \r\n");
      out.write("\t\t\t           {\r\n");
      out.write("\t\t\t               alert('something else other than 200 was returned');\r\n");
      out.write("\t\t\t           }\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    };\r\n");
      out.write("\t\t\t    var check= document.getElementById('iMode').checked\r\n");
      out.write("\t\t\t    if(!check){\r\n");
      out.write("\t\t\t\t    if(confirm('Si desactiva el Modo Inventario, cuando lo vuelva a activar perdera los datos del conteo. Esta Seguro?')){\r\n");
      out.write("\t\t\t\t    \txmlhttp.open(\"POST\", \"");
      out.print(basePath);
      out.write("/ActivarModoInventario.do?activo=\"+check, true);\r\n");
      out.write("\t\t\t\t    \txmlhttp.send();\r\n");
      out.write("\t\t\t\t    \treq='';\r\n");
      out.write("\t\t\t    \t}\r\n");
      out.write("\t\t\t    \telse{\r\n");
      out.write("\t\t\t    \t location.reload();\r\n");
      out.write("\t\t\t    \t}\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t    else{\r\n");
      out.write("\t\t\t    \tif(confirm('Esta seguro que desea activar el Modo Inventario')){\r\n");
      out.write("\t\t\t\t    \t xmlhttp.open(\"POST\", \"");
      out.print(basePath);
      out.write("/ActivarModoInventario.do?activo=\"+check, true);\r\n");
      out.write("\t\t\t\t\t     xmlhttp.send();\r\n");
      out.write("\t\t\t\t\t     req='';\r\n");
      out.write("\t\t\t    \t}\r\n");
      out.write("\t\t\t    \telse{\r\n");
      out.write("\t\t\t    \t location.reload();\r\n");
      out.write("\t\t\t    \t}\r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\r\n");
      out.write("        \t}\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("       \t\tfunction sincro()\r\n");
      out.write("       \t\t{\r\n");
      out.write("       \t\t\tif(confirm('Esta seguro que desea Sincronizar Encuentra?'))\r\n");
      out.write("       \t\t\t{\r\n");
      out.write("\t       \t\t\t  var btn = document.getElementById(\"btnSincronizar\");\r\n");
      out.write("\t\t\t\t      // disable button\r\n");
      out.write("\t\t\t\t      btn.disabled = true; \r\n");
      out.write("\t\t\t\t      // add spinner to button\r\n");
      out.write("\t\t\t\t      btn.innerHTML ='<span class=\"spinner-border spinner-border-sm\" role=\"status\" aria-hidden=\"true\"></span> Sincronizando...';\r\n");
      out.write("\t\t\t      \r\n");
      out.write("       \t\t\t\tlocation.assign('");
      out.print(basePath);
      out.write("/sincroManual.do');\r\n");
      out.write("       \t\t\t}\r\n");
      out.write("       \t\t}\r\n");
      out.write("       </script>\r\n");
      out.write("       \r\n");
      out.write("       <script>\r\n");
      out.write("       $('.sweet-sincro').on('click', function() {\r\n");
      out.write("        swal({\r\n");
      out.write("                title: \"Atencion!\",\r\n");
      out.write("                text: \"Esta seguro que desea Sincronizar Encuentra?\",\r\n");
      out.write("                icon: \"warning\",\r\n");
      out.write("                buttons: true,\r\n");
      out.write("                dangerMode: true,\r\n");
      out.write("            })\r\n");
      out.write("            .then((willDelete) => {\r\n");
      out.write("                if (willDelete) {\r\n");
      out.write("                \tvar btn = document.getElementById(\"btnSincronizar\");\r\n");
      out.write("\t\t\t\t      // disable button\r\n");
      out.write("\t\t\t\t      btn.disabled = true; \r\n");
      out.write("\t\t\t\t      // add spinner to button\r\n");
      out.write("\t\t\t\t      btn.innerHTML ='<span class=\"spinner-border spinner-border-sm\" role=\"status\" aria-hidden=\"true\"></span> Sincronizando...';\r\n");
      out.write("\t\t\t      \r\n");
      out.write("     \t\t\t\tlocation.assign('");
      out.print(basePath);
      out.write("/sincroManual.do');\r\n");
      out.write("                } else {\r\n");
      out.write("                    \r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("    });\r\n");
      out.write("       </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- [ Main Content ] end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Warning Section start -->\r\n");
      out.write("    <!-- Older IE warning message -->\r\n");
      out.write("    <!--[if lt IE 11]>\r\n");
      out.write("        <div class=\"ie-warning\">\r\n");
      out.write("            <h1>Warning!!</h1>\r\n");
      out.write("            <p>You are using an outdated version of Internet Explorer, please upgrade\r\n");
      out.write("               <br/>to any of the following web browsers to access this website.\r\n");
      out.write("            </p>\r\n");
      out.write("            <div class=\"iew-container\">\r\n");
      out.write("                <ul class=\"iew-download\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"http://www.google.com/chrome/\">\r\n");
      out.write("                            <img src=\"");
      out.print(basePath);
      out.write("v3/assets/images/browser/chrome.png\" alt=\"Chrome\">\r\n");
      out.write("                            <div>Chrome</div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"https://www.mozilla.org/en-US/firefox/new/\">\r\n");
      out.write("                            <img src=\"");
      out.print(basePath);
      out.write("v3/assets/images/browser/firefox.png\" alt=\"Firefox\">\r\n");
      out.write("                            <div>Firefox</div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"http://www.opera.com\">\r\n");
      out.write("                            <img src=\"");
      out.print(basePath);
      out.write("v3/assets/images/browser/opera.png\" alt=\"Opera\">\r\n");
      out.write("                            <div>Opera</div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"https://www.apple.com/safari/\">\r\n");
      out.write("                            <img src=\"");
      out.print(basePath);
      out.write("v3/assets/images/browser/safari.png\" alt=\"Safari\">\r\n");
      out.write("                            <div>Safari</div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\">\r\n");
      out.write("                            <img src=\"");
      out.print(basePath);
      out.write("v3/assets/images/browser/ie.png\" alt=\"\">\r\n");
      out.write("                            <div>IE (11 & above)</div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>Sorry for the inconvenience!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <!-- Warning Section Ends -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Required Js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/js/vendor-all.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/js/pcoded.js\"></script>\r\n");
      out.write("    <!-- amchart js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/amchart/js/amcharts.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/amchart/js/gauge.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/amchart/js/serial.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/amchart/js/light.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/amchart/js/pie.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/amchart/js/ammap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/amchart/js/usaLow.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/amchart/js/radar.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/amchart/js/worldLow.js\"></script>\r\n");
      out.write("    <!-- notification Js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/notification/js/bootstrap-growl.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- dashboard-custom js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/js/pages/dashboard-custom.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- datepicker js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/js/pages/ac-datepicker.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("     <!-- datatable Js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/data-tables/js/datatables.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/js/pages/tbl-datatable-custom.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/data-tables/js/rowgroup.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     <!-- select 2 Js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/select2/js/select2.full.min.js\"></script>\r\n");
      out.write(" \t\r\n");
      out.write(" \t <!-- modal-window-effects Js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/modal-window-effects/js/classie.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/modal-window-effects/js/modalEffects.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- bootstrap-tagsinput-latest Js -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/bootstrap-tagsinput-latest/js/bootstrap-tagsinput.min.js\"></script>\r\n");
      out.write("    <!-- bootstrap-maxlength Js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/bootstrap-maxlength/js/bootstrap-maxlength.min.js\"></script>\r\n");
      out.write("     <!-- form-advance custom js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/js/pages/form-advance-custom.js\"></script>\r\n");
      out.write("    <!-- Toolbar Js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/toolbar/js/jquery.toolbar.min.js\"></script>\r\n");
      out.write("    <!-- sweet alert Js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/sweetalert/js/sweetalert.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/js/pages/ac-alert.js\"></script>\r\n");
      out.write("    <!-- toolbar Js -->\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/plugins/toolbar/js/jquery.toolbar.min.js\"></script>    \r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("v3/assets/js/pages/ac-toolbar.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      if (_jspx_meth_c_005fremove_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /v3/util/footer.jsp(36,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("d");
      // /v3/util/footer.jsp(36,13) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${equipos}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t  \t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /v3/util/footer.jsp(37,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id==uLogeado.idEquipo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" selected=\"selected\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /v3/util/footer.jsp(40,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id!=uLogeado.idEquipo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /v3/util/footer.jsp(80,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("d");
      // /v3/util/footer.jsp(80,13) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depositoU}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
            if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t  \t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /v3/util/footer.jsp(81,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id==uLogeado.deposito}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" selected=\"selected\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /v3/util/footer.jsp(84,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id!=uLogeado.deposito}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent(null);
      // /v3/util/footer.jsp(457,4) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("menError");
      // /v3/util/footer.jsp(457,4) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
