
package clientesVisual_Store.Std.clienteWSNAD;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SWNadWeb service = new SWNadWeb();
* SWNadWebSoap portType = service.getSWNadWebSoap();
* portType.grabarOrdenVenta(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SWNadWeb", targetNamespace = "http://tempuri.org/VSServicioWeb/SWNadWeb", wsdlLocation = "http://10.108.0.19:8085/dtds/swnadweb.asmx.xml")
public class SWNadWeb extends Service {

	private final static URL SWNADWEB_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(SWNadWeb.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = SWNadWeb.class.getResource(".");
			url = new URL(baseUrl, "http://10.108.0.19:8085/dtds/swnadweb.asmx.xml");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://10.108.0.19:8085/dtds/swnadweb.asmx.xml', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SWNADWEB_WSDL_LOCATION = url;
	}

	public SWNadWeb(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SWNadWeb() {
		super(SWNADWEB_WSDL_LOCATION, new QName("http://tempuri.org/VSServicioWeb/SWNadWeb", "SWNadWeb"));
	}

	/**
	 * 
	 * @return returns SWNadWebSoap
	 */
	@WebEndpoint(name = "SWNadWebSoap")
	public SWNadWebSoap getSWNadWebSoap() {
		return super.getPort(new QName("http://tempuri.org/VSServicioWeb/SWNadWeb", "SWNadWebSoap"),
				SWNadWebSoap.class);
	}

	/**
	 * 
	 * @return returns SWNadWebSoap
	 */
	@WebEndpoint(name = "SWNadWebSoap12")
	public SWNadWebSoap getSWNadWebSoap12() {
		return super.getPort(new QName("http://tempuri.org/VSServicioWeb/SWNadWeb", "SWNadWebSoap12"),
				SWNadWebSoap.class);
	}

}
