
package integraciones.erp.visualStore.stadium.v1;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SWStadiumSoap", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium")
public interface SWStadiumSoap {

	/**
	 * Grabar Transferencia
	 * 
	 * @param xmlDetalle
	 * @param idEquipo
	 * @param nroEmpresa
	 * @param hora
	 * @param idUsuario
	 * @param confirmada
	 * @param comentario
	 * @param idRazonDocumento
	 * @param idTienda
	 * @param idDepDestino
	 * @param fecha
	 * @param grabarTransferenciaResult
	 * @param mensaje
	 * @param idDeposito
	 */
	@WebMethod(operationName = "GrabarTransferencia", action = "http://tempuri.org/VSServicioWeb/SWStadium/GrabarTransferencia")
	@RequestWrapper(localName = "GrabarTransferencia", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarTransferencia")
	@ResponseWrapper(localName = "GrabarTransferenciaResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarTransferenciaResponse")
	public void grabarTransferencia(
			@WebParam(name = "Mensaje", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensaje,
			@WebParam(name = "IdUsuario", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long idUsuario,
			@WebParam(name = "IdEquipo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idEquipo,
			@WebParam(name = "IdTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idTienda,
			@WebParam(name = "NroEmpresa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long nroEmpresa,
			@WebParam(name = "IdDeposito", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idDeposito,
			@WebParam(name = "Fecha", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String fecha,
			@WebParam(name = "Hora", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String hora,
			@WebParam(name = "Comentario", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String comentario,
			@WebParam(name = "IdDepDestino", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idDepDestino,
			@WebParam(name = "IdRazonDocumento", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idRazonDocumento,
			@WebParam(name = "xmlDetalle", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String xmlDetalle,
			@WebParam(name = "Confirmada", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") boolean confirmada,
			@WebParam(name = "GrabarTransferenciaResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<Integer> grabarTransferenciaResult);

	/**
	 * Grabar Transferencia en la Tienda
	 * 
	 * @param xmlDetalle
	 * @param idEquipo
	 * @param nroEmpresa
	 * @param hora
	 * @param idUsuario
	 * @param confirmada
	 * @param grabarTransferenciaTiendaResult
	 * @param comentario
	 * @param idRazonDocumento
	 * @param idTienda
	 * @param idDepDestino
	 * @param fecha
	 * @param mensaje
	 * @param idDeposito
	 */
	@WebMethod(operationName = "GrabarTransferenciaTienda", action = "http://tempuri.org/VSServicioWeb/SWStadium/GrabarTransferenciaTienda")
	@RequestWrapper(localName = "GrabarTransferenciaTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarTransferenciaTienda")
	@ResponseWrapper(localName = "GrabarTransferenciaTiendaResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarTransferenciaTiendaResponse")
	public void grabarTransferenciaTienda(
			@WebParam(name = "Mensaje", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensaje,
			@WebParam(name = "IdUsuario", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long idUsuario,
			@WebParam(name = "IdEquipo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idEquipo,
			@WebParam(name = "IdTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idTienda,
			@WebParam(name = "NroEmpresa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long nroEmpresa,
			@WebParam(name = "IdDeposito", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idDeposito,
			@WebParam(name = "Fecha", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String fecha,
			@WebParam(name = "Hora", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String hora,
			@WebParam(name = "Comentario", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String comentario,
			@WebParam(name = "IdDepDestino", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idDepDestino,
			@WebParam(name = "IdRazonDocumento", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idRazonDocumento,
			@WebParam(name = "xmlDetalle", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String xmlDetalle,
			@WebParam(name = "Confirmada", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") boolean confirmada,
			@WebParam(name = "GrabarTransferenciaTiendaResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<Integer> grabarTransferenciaTiendaResult);

	/**
	 * Grabar Recepcion
	 * 
	 * @param xmlDetalle
	 * @param idEquipo
	 * @param tipoAfecta
	 * @param idDepRecepcion
	 * @param nroRemito
	 * @param nroEmpresa
	 * @param fechaRecep
	 * @param hora
	 * @param idUsuario
	 * @param serieRemito
	 * @param grabarRecepcionResult
	 * @param comentario
	 * @param idTienda
	 * @param numeroDoc
	 * @param idProveedor
	 * @param mensaje
	 * @param idDeposito
	 */
	@WebMethod(operationName = "GrabarRecepcion", action = "http://tempuri.org/VSServicioWeb/SWStadium/GrabarRecepcion")
	@RequestWrapper(localName = "GrabarRecepcion", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarRecepcion")
	@ResponseWrapper(localName = "GrabarRecepcionResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarRecepcionResponse")
	public void grabarRecepcion(
			@WebParam(name = "Mensaje", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensaje,
			@WebParam(name = "IdUsuario", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long idUsuario,
			@WebParam(name = "IdEquipo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idEquipo,
			@WebParam(name = "IdTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idTienda,
			@WebParam(name = "NroEmpresa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long nroEmpresa,
			@WebParam(name = "TipoAfecta", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String tipoAfecta,
			@WebParam(name = "IdDeposito", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idDeposito,
			@WebParam(name = "IdDepRecepcion", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idDepRecepcion,
			@WebParam(name = "FechaRecep", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String fechaRecep,
			@WebParam(name = "Hora", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String hora,
			@WebParam(name = "Comentario", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String comentario,
			@WebParam(name = "NumeroDoc", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int numeroDoc,
			@WebParam(name = "IdProveedor", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long idProveedor,
			@WebParam(name = "SerieRemito", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String serieRemito,
			@WebParam(name = "NroRemito", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int nroRemito,
			@WebParam(name = "xmlDetalle", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String xmlDetalle,
			@WebParam(name = "GrabarRecepcionResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<Integer> grabarRecepcionResult);

	/**
	 * Actualizar Mail Cliente
	 * 
	 * @param actualizarMailCliResult
	 * @param mail
	 * @param numeroCliente
	 * @param idEmpresa
	 * @param mensaje
	 * @param tipoMail
	 * @param idTienda
	 */
	@WebMethod(operationName = "ActualizarMailCli", action = "http://tempuri.org/VSServicioWeb/SWStadium/ActualizarMailCli")
	@RequestWrapper(localName = "ActualizarMailCli", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.ActualizarMailCli")
	@ResponseWrapper(localName = "ActualizarMailCliResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.ActualizarMailCliResponse")
	public void actualizarMailCli(
			@WebParam(name = "Mensaje", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensaje,
			@WebParam(name = "NumeroCliente", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long numeroCliente,
			@WebParam(name = "TipoMail", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short tipoMail,
			@WebParam(name = "Mail", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String mail,
			@WebParam(name = "IdTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idTienda,
			@WebParam(name = "IdEmpresa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long idEmpresa,
			@WebParam(name = "ActualizarMailCliResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<Boolean> actualizarMailCliResult);

	/**
	 * Actualizar Datos del Cliente
	 * 
	 * @param mail
	 * @param numeroCliente
	 * @param actualizarDatosCliResult
	 * @param nombre
	 * @param numeroCliDig
	 * @param idTienda
	 * @param numeroCliAnterior
	 * @param fechaNac
	 * @param apellido
	 * @param celular
	 * @param idEmpresa
	 * @param mensaje
	 * @param sexo
	 * @param tipoMail
	 */
	@WebMethod(operationName = "ActualizarDatosCli", action = "http://tempuri.org/VSServicioWeb/SWStadium/ActualizarDatosCli")
	@RequestWrapper(localName = "ActualizarDatosCli", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.ActualizarDatosCli")
	@ResponseWrapper(localName = "ActualizarDatosCliResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.ActualizarDatosCliResponse")
	public void actualizarDatosCli(
			@WebParam(name = "Mensaje", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensaje,
			@WebParam(name = "NumeroCliAnterior", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long numeroCliAnterior,
			@WebParam(name = "NumeroCliente", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long numeroCliente,
			@WebParam(name = "NumeroCliDig", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String numeroCliDig,
			@WebParam(name = "TipoMail", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short tipoMail,
			@WebParam(name = "Mail", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String mail,
			@WebParam(name = "Sexo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String sexo,
			@WebParam(name = "FechaNac", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String fechaNac,
			@WebParam(name = "Nombre", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String nombre,
			@WebParam(name = "Apellido", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String apellido,
			@WebParam(name = "Celular", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String celular,
			@WebParam(name = "IdTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idTienda,
			@WebParam(name = "IdEmpresa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long idEmpresa,
			@WebParam(name = "ActualizarDatosCliResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<Boolean> actualizarDatosCliResult);

	/**
	 * Grabar Codigo de Barras
	 * 
	 * @param idArticulo
	 * @param eliminar
	 * @param nroEmpresa
	 * @param nroBarra
	 * @param mensaje
	 * @param grabarArtBarraResult
	 * @param idTienda
	 */
	@WebMethod(operationName = "GrabarArtBarra", action = "http://tempuri.org/VSServicioWeb/SWStadium/GrabarArtBarra")
	@RequestWrapper(localName = "GrabarArtBarra", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarArtBarra")
	@ResponseWrapper(localName = "GrabarArtBarraResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarArtBarraResponse")
	public void grabarArtBarra(
			@WebParam(name = "Mensaje", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensaje,
			@WebParam(name = "IdTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idTienda,
			@WebParam(name = "NroEmpresa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long nroEmpresa,
			@WebParam(name = "IdArticulo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String idArticulo,
			@WebParam(name = "NroBarra", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String nroBarra,
			@WebParam(name = "Eliminar", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") boolean eliminar,
			@WebParam(name = "GrabarArtBarraResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<Boolean> grabarArtBarraResult);

	/**
	 * Grabar Articulo
	 * 
	 * @param descripcion
	 * @param idImpVta2
	 * @param usuAlta
	 * @param inactivo
	 * @param unidadEmpaque
	 * @param fecModif
	 * @param idCostoImp
	 * @param idProveedor
	 * @param idCategoria
	 * @param idMarca
	 * @param idGarantiaCli
	 * @param compraMinimo
	 * @param idUniMed
	 * @param diasEntrega
	 * @param codParaProv
	 * @param usuModif
	 * @param descDespa
	 * @param idEnvase
	 * @param stockMinimo
	 * @param idGenero
	 * @param sujDescuento
	 * @param idPaisOrigen
	 * @param descIdioma1
	 * @param descIdioma2
	 * @param descIdioma3
	 * @param nroEmpresa
	 * @param idTipoArticulo
	 * @param idTienda
	 * @param idProvAlter
	 * @param coleccion
	 * @param porcGanancia
	 * @param idGarantiaProv
	 * @param idImpCom1
	 * @param grabarArticuloResult
	 * @param idImpCom2
	 * @param fecAlta
	 * @param idSeccion
	 * @param idArticulo
	 * @param comentario
	 * @param idRubro
	 * @param idTemporada
	 * @param stockMaximo
	 * @param importado
	 * @param mantieneStock
	 * @param codNadisa
	 * @param idEscala
	 * @param idProvOri
	 * @param idClase
	 * @param mensaje
	 * @param idImpVta1
	 */
	@WebMethod(operationName = "GrabarArticulo", action = "http://tempuri.org/VSServicioWeb/SWStadium/GrabarArticulo")
	@RequestWrapper(localName = "GrabarArticulo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarArticulo")
	@ResponseWrapper(localName = "GrabarArticuloResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarArticuloResponse")
	public void grabarArticulo(
			@WebParam(name = "Mensaje", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensaje,
			@WebParam(name = "IdTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idTienda,
			@WebParam(name = "NroEmpresa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long nroEmpresa,
			@WebParam(name = "CodNadisa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String codNadisa,
			@WebParam(name = "CodParaProv", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String codParaProv,
			@WebParam(name = "Coleccion", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short coleccion,
			@WebParam(name = "Comentario", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String comentario,
			@WebParam(name = "CompraMinimo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") BigDecimal compraMinimo,
			@WebParam(name = "DescDespa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String descDespa,
			@WebParam(name = "DescIdioma1", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String descIdioma1,
			@WebParam(name = "DescIdioma2", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String descIdioma2,
			@WebParam(name = "DescIdioma3", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String descIdioma3,
			@WebParam(name = "Descripcion", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String descripcion,
			@WebParam(name = "DiasEntrega", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int diasEntrega,
			@WebParam(name = "FecAlta", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String fecAlta,
			@WebParam(name = "FecModif", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String fecModif,
			@WebParam(name = "IdArticulo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String idArticulo,
			@WebParam(name = "IdCategoria", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idCategoria,
			@WebParam(name = "IdClase", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idClase,
			@WebParam(name = "IdCostoImp", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idCostoImp,
			@WebParam(name = "IdEnvase", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idEnvase,
			@WebParam(name = "IdEscala", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String idEscala,
			@WebParam(name = "IdGarantiaCli", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idGarantiaCli,
			@WebParam(name = "IdGarantiaProv", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idGarantiaProv,
			@WebParam(name = "IdGenero", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idGenero,
			@WebParam(name = "IdImpCom1", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idImpCom1,
			@WebParam(name = "IdImpCom2", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idImpCom2,
			@WebParam(name = "IdImpVta1", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idImpVta1,
			@WebParam(name = "IdImpVta2", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idImpVta2,
			@WebParam(name = "IdMarca", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idMarca,
			@WebParam(name = "IdPaisOrigen", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idPaisOrigen,
			@WebParam(name = "IdProvAlter", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long idProvAlter,
			@WebParam(name = "IdProveedor", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long idProveedor,
			@WebParam(name = "IdProvOri", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long idProvOri,
			@WebParam(name = "IdRubro", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idRubro,
			@WebParam(name = "IdSeccion", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idSeccion,
			@WebParam(name = "IdTemporada", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idTemporada,
			@WebParam(name = "IdTipoArticulo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idTipoArticulo,
			@WebParam(name = "IdUniMed", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idUniMed,
			@WebParam(name = "Importado", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") boolean importado,
			@WebParam(name = "Inactivo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short inactivo,
			@WebParam(name = "MantieneStock", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") boolean mantieneStock,
			@WebParam(name = "PorcGanancia", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") BigDecimal porcGanancia,
			@WebParam(name = "StockMaximo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") BigDecimal stockMaximo,
			@WebParam(name = "StockMinimo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") BigDecimal stockMinimo,
			@WebParam(name = "SujDescuento", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") boolean sujDescuento,
			@WebParam(name = "UnidadEmpaque", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int unidadEmpaque,
			@WebParam(name = "UsuAlta", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long usuAlta,
			@WebParam(name = "UsuModif", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long usuModif,
			@WebParam(name = "GrabarArticuloResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<Boolean> grabarArticuloResult);

	/**
	 * Grabar Orden de Venta
	 * 
	 * @param grabarOrdenVentaXmlResult
	 * @param mensError
	 * @param xmlDatos
	 */
	@WebMethod(operationName = "GrabarOrdenVentaXml", action = "http://tempuri.org/VSServicioWeb/SWStadium/GrabarOrdenVentaXml")
	@RequestWrapper(localName = "GrabarOrdenVentaXml", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarOrdenVentaXml")
	@ResponseWrapper(localName = "GrabarOrdenVentaXmlResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarOrdenVentaXmlResponse")
	public void grabarOrdenVentaXml(
			@WebParam(name = "MensError", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensError,
			@WebParam(name = "xmlDatos", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String xmlDatos,
			@WebParam(name = "GrabarOrdenVentaXmlResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<Integer> grabarOrdenVentaXmlResult);

	/**
	 * Grabar PersonaCliente
	 * 
	 * @param grabarPersonaClienteXmlResult
	 * @param mensError
	 * @param xmlDatos
	 */
	@WebMethod(operationName = "GrabarPersonaClienteXml", action = "http://tempuri.org/VSServicioWeb/SWStadium/GrabarPersonaClienteXml")
	@RequestWrapper(localName = "GrabarPersonaClienteXml", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarPersonaClienteXml")
	@ResponseWrapper(localName = "GrabarPersonaClienteXmlResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.GrabarPersonaClienteXmlResponse")
	public void grabarPersonaClienteXml(
			@WebParam(name = "MensError", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensError,
			@WebParam(name = "xmlDatos", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String xmlDatos,
			@WebParam(name = "GrabarPersonaClienteXmlResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<String> grabarPersonaClienteXmlResult);

	/**
	 * StockSucursalesEmp
	 * 
	 * @param idArticulo
	 * @param consStockEmpXmlResult
	 * @param depositos
	 * @param idEmpresa
	 * @param mensError
	 */
	@WebMethod(operationName = "ConsStockEmpXml", action = "http://tempuri.org/VSServicioWeb/SWStadium/ConsStockEmpXml")
	@RequestWrapper(localName = "ConsStockEmpXml", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.ConsStockEmpXml")
	@ResponseWrapper(localName = "ConsStockEmpXmlResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.ConsStockEmpXmlResponse")
	public void consStockEmpXml(
			@WebParam(name = "MensError", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensError,
			@WebParam(name = "IdArticulo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String idArticulo,
			@WebParam(name = "Depositos", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String depositos,
			@WebParam(name = "IdEmpresa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int idEmpresa,
			@WebParam(name = "ConsStockEmpXmlResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<String> consStockEmpXmlResult);

	/**
	 * Confirmar Transferencia de Stock
	 * 
	 * @param idDepDestino
	 * @param xmlDetalle
	 * @param idEquipo
	 * @param nroEmpresa
	 * @param numeroDoc
	 * @param mensaje
	 * @param nroUsuario
	 * @param idDepOrigen
	 * @param idTienda
	 * @param confirmarTransferenciaResult
	 */
	@WebMethod(operationName = "ConfirmarTransferencia", action = "http://tempuri.org/VSServicioWeb/SWStadium/ConfirmarTransferencia")
	@RequestWrapper(localName = "ConfirmarTransferencia", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.ConfirmarTransferencia")
	@ResponseWrapper(localName = "ConfirmarTransferenciaResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.ConfirmarTransferenciaResponse")
	public void confirmarTransferencia(
			@WebParam(name = "Mensaje", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensaje,
			@WebParam(name = "NroUsuario", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long nroUsuario,
			@WebParam(name = "IdEquipo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idEquipo,
			@WebParam(name = "IdTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idTienda,
			@WebParam(name = "NroEmpresa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long nroEmpresa,
			@WebParam(name = "IdDepOrigen", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idDepOrigen,
			@WebParam(name = "IdDepDestino", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idDepDestino,
			@WebParam(name = "NumeroDoc", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int numeroDoc,
			@WebParam(name = "xmlDetalle", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String xmlDetalle,
			@WebParam(name = "ConfirmarTransferenciaResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<Boolean> confirmarTransferenciaResult);

	/**
	 * Confirmar Transferencia de Stock en una Tienda
	 * 
	 * @param idDepDestino
	 * @param xmlDetalle
	 * @param idEquipo
	 * @param nroEmpresa
	 * @param numeroDoc
	 * @param confirmarTransferenciaTiendaResult
	 * @param mensaje
	 * @param nroUsuario
	 * @param idDepOrigen
	 * @param idTienda
	 */
	@WebMethod(operationName = "ConfirmarTransferenciaTienda", action = "http://tempuri.org/VSServicioWeb/SWStadium/ConfirmarTransferenciaTienda")
	@RequestWrapper(localName = "ConfirmarTransferenciaTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.ConfirmarTransferenciaTienda")
	@ResponseWrapper(localName = "ConfirmarTransferenciaTiendaResponse", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", className = "clientesVisual_Store.Std.clienteWSVS.ConfirmarTransferenciaTiendaResponse")
	public void confirmarTransferenciaTienda(
			@WebParam(name = "Mensaje", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.INOUT) Holder<String> mensaje,
			@WebParam(name = "NroUsuario", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long nroUsuario,
			@WebParam(name = "IdEquipo", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idEquipo,
			@WebParam(name = "IdTienda", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idTienda,
			@WebParam(name = "NroEmpresa", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") long nroEmpresa,
			@WebParam(name = "IdDepOrigen", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idDepOrigen,
			@WebParam(name = "IdDepDestino", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") short idDepDestino,
			@WebParam(name = "NumeroDoc", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") int numeroDoc,
			@WebParam(name = "xmlDetalle", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium") String xmlDetalle,
			@WebParam(name = "ConfirmarTransferenciaTiendaResult", targetNamespace = "http://tempuri.org/VSServicioWeb/SWStadium", mode = WebParam.Mode.OUT) Holder<Boolean> confirmarTransferenciaTiendaResult);

}
