
package integraciones.erp.ascher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CargaArticulosPaginadoSoapPort", targetNamespace = "PpGg")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CargaArticulosPaginadoSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns ppgg.CargaArticulosPaginadoExecuteResponse
     */
    @WebMethod(operationName = "Execute", action = "PpGgaction/ACARGAARTICULOSPAGINADO.Execute")
    @WebResult(name = "CargaArticulosPaginado.ExecuteResponse", targetNamespace = "PpGg", partName = "parameters")
    public CargaArticulosPaginadoExecuteResponse execute(
        @WebParam(name = "CargaArticulosPaginado.Execute", targetNamespace = "PpGg", partName = "parameters")
        CargaArticulosPaginadoExecute parameters);

}
